# Generated by Django 6.0.3 on 2026-03-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='contactPhone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
