# Generated by Django 6.0.3 on 2026-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_contactphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='contactPhone',
        ),
    ]
